/**
 * Dockstore API
 * This describes the dockstore API, a webservice that manages pairs of Docker images and associated metadata such as CWL documents and Dockerfiles used to build those images
 *
 * OpenAPI spec version: 1.3.0
 * Contact: theglobalalliance@genomicsandhealth.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Describes this registry to better allow for mirroring and indexing.
 */
export interface Metadata {
    /**
     * The version of this registry
     */
    version: string;
    /**
     * The version of the GA4GH tool-registry API supported by this registry
     */
    api_version: string;
    /**
     * A country code for the registry (ISO 3166-1 alpha-3)
     */
    country?: string;
    /**
     * A friendly name that can be used in addition to the hostname to describe a registry
     */
    friendly_name?: string;
}
