-- This SQL will create a reasonable facsimile of a Notebook and associated version and sourcefiles.
-- It was generated by hand from a webservice database dump on 16/Mar/2023,
-- after an import of the "simple-published-v1" tag of the "dockstore-testing/simple-notebook" repo.

--
-- Data for Name: author; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.author (id, affiliation, dbcreatedate, dbupdatedate, email, name, role, versionid) FROM stdin;
1001	\N	2023-03-16 16:38:14.96	2023-03-16 16:38:14.96	\N	Author One	\N	1000
1002	\N	2023-03-16 16:38:14.964	2023-03-16 16:38:14.964	\N	Author Two	\N	1000
\.

--
-- Data for Name: entry_defaultpaths; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.entry_defaultpaths (entry_id, path, filetype) FROM stdin;
1000	/.dockstore.yml	DOCKSTORE_CWL
\.

--
-- Data for Name: notebook; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.notebook (id, author, conceptdoi, dbcreatedate, dbupdatedate, description, email, giturl, ispublished, lastmodified, lastupdated, licensename, topicid, checkerid, descriptortype, descriptortypesubclass, forumurl, mode, organization, repository, sourcecontrol, workflowname, actualdefaultversion, topicautomatic, topicmanual, topicselection) FROM stdin;
1000	\N	\N	2023-03-16 16:38:14.926	2023-03-16 16:38:14.994	\N	\N	git@github.com:dockstore-testing/simple-notebook.git	t	2023-02-14 14:43:15	2023-03-16 16:38:13.8	\N	\N	\N	jupyter	python	\N	DOCKSTORE_YML	dockstore-testing	simple-notebook	github.com	\N	\N	\N	\N	AUTOMATIC
\.

--
-- Data for Name: fullworkflowpath; Type: TABLE DATA; Schema: public; Owner: dockstore
--

-- COPY public.fullworkflowpath (id, organization, repository, sourcecontrol, workflowname) FROM stdin;
-- 1000	dockstore-testing	simple-notebook	github.com	\N
-- \.

--
-- Data for Name: sourcefile; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.sourcefile (id, content, path, type, dbcreatedate, dbupdatedate, absolutepath, frozen) FROM stdin;
1000	version: 1.2\nnotebooks:\n  - path: /notebook.ipynb\n    publish: true\n	/.dockstore.yml	DOCKSTORE_YML	2023-03-16 16:38:14.982	2023-03-16 16:38:14.982	/.dockstore.yml	f
1001	{\n  "nbformat": 4,\n  "nbformat_minor": 0,\n  "metadata": {\n    "colab": {\n      "provenance": [],\n      "authorship_tag": "ABX9TyOvihAxHYcHRNfCqilp5Zgg",\n      "include_colab_link": true\n    },\n    "kernelspec": {\n      "name": "python3",\n      "display_name": "Python 3"\n    },\n    "language_info": {\n      "name": "python"\n    },\n    "authors": [\n      { "name": "Author Two" },\n      { "name": "Author One" }\n    ]\n  },\n  "cells": [\n    {\n      "cell_type": "markdown",\n      "source": [\n        "A simple notebook."\n      ],\n      "metadata": {\n        "id": "PSOLAGuMMaYg"\n      }\n    },\n    {\n      "cell_type": "code",\n      "execution_count": null,\n      "metadata": {\n        "colab": {\n          "base_uri": "https://localhost:8080/"\n        },\n        "id": "z9GVmXMWFnWV",\n        "outputId": "f33dda6a-d0fd-40ee-de84-e726fafab5b9"\n      },\n      "outputs": [\n        {\n          "output_type": "stream",\n          "name": "stdout",\n          "text": [\n            "Hello world!\\n"\n          ]\n        }\n      ],\n      "source": [\n        "print(\\"Hello world!\\")"\n      ]\n    }\n  ]\n}\n	/notebook.ipynb	DOCKSTORE_JUPYTER	2023-03-16 16:38:14.982	2023-03-16 16:38:14.982	/notebook.ipynb	f
\.

--
-- Data for Name: sourcefile_metadata; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.sourcefile_metadata (id, typeversion) FROM stdin;
1000	\N
1001	4.0
\.

--
-- Data for Name: user_entry; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.user_entry (userid, entryid) FROM stdin;
1	1000
\.

--
-- Data for Name: version_metadata; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.version_metadata (doistatus, doiurl, hidden, verified, verifiedsource, id, description, description_source, dbcreatedate, dbupdatedate, publicaccessibletestparameterfile, descriptortypeversions) FROM stdin;
NOT_REQUESTED	\N	f	f	\N	1000	\N	\N	2023-03-16 16:38:14.989	2023-03-16 16:38:14.989	\N	4.0
\.

--
-- Data for Name: version_sourcefile; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.version_sourcefile (versionid, sourcefileid) FROM stdin;
1000	1000
1000	1001
\.

--
-- Data for Name: validation; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.validation (id, dbcreatedate, dbupdatedate, message, type, valid) FROM stdin;
1001	2023-03-16 16:38:14.986	2023-03-16 16:38:14.986	{}	DOCKSTORE_YML	t
1002	2023-03-16 16:38:14.989	2023-03-16 16:38:14.989	{}	DOCKSTORE_JUPYTER	t
1003	2023-03-16 16:38:14.989	2023-03-16 16:38:14.989	{}	DOCKSTORE_NOTEBOOK_TEST_FILE	t
\.

--
-- Data for Name: version_validation; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.version_validation (versionid, validationid) FROM stdin;
1000	1001
1000	1002
1000	1003
\.

--
-- Data for Name: workflowversion; Type: TABLE DATA; Schema: public; Owner: dockstore
--

COPY public.workflowversion (id, dirtybit, lastmodified, name, reference, valid, workflowpath, dbcreatedate, dbupdatedate, referencetype, versioneditor_id, commitid, frozen, parentid, islegacyversion, dagjson, tooltablejson, synced, userfiles, readmepath, kernelimagepath) FROM stdin;
1000	f	2023-02-14 14:43:15	simple-published-v1	simple-published-v1	t	/notebook.ipynb	2023-03-16 16:38:14.957	2023-03-16 16:38:14.957	TAG	\N	a69804f0c1ce5b7a260238ea5883c3876ab6b56d	f	1000	f	\N	\N	t	\N	\N	\N
\.

