version: 2
updates:

  # Maintain dependencies for GitHub Actions, path is indeed "/" https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm 
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # start with security updates only https://stackoverflow.com/a/68254421
    open-pull-requests-limit: 0  
