import { Injectable } from '@angular/core';
import { AlertService } from '../../../alert/state/alert.service';
import { AccessLink, Doi, Workflow, WorkflowsService } from '../../../openapi';
import { WorkflowService } from '../../../state/workflow.service';
import { WorkflowQuery } from 'app/shared/state/workflow.query';
import { InfoTabService } from 'app/workflow/info-tab/info-tab.service';
import { Observable, throwError } from 'rxjs';
import { catchError, tap } from 'rxjs/operators';

@Injectable()
export class ManageDoisDialogService {
  constructor(
    private alertService: AlertService,
    private workflowsService: WorkflowsService,
    private workflowService: WorkflowService,
    private workflowQuery: WorkflowQuery,
    private infoTabService: InfoTabService
  ) {}

  saveDoiSelection(entry: Workflow, doiSelection: Doi.InitiatorEnum) {
    this.alertService.start('Saving DOI selection');
    const newEntryForUpdate = this.infoTabService.getPartialEntryForUpdate({ ...entry, doiSelection: doiSelection });

    this.workflowsService.updateWorkflow(entry.id, newEntryForUpdate).subscribe(
      (response) => {
        this.alertService.detailedSuccess();
        this.workflowService.setWorkflow({ ...this.workflowQuery.getActive(), doiSelection: response.doiSelection });
      },
      (error) => {
        this.alertService.detailedError(error);
      }
    );
  }

  toggleAutoDoiGeneration(entry: Workflow, isAutoDoiEnabled: boolean) {
    this.alertService.start((isAutoDoiEnabled ? 'Enabling' : 'Disabling') + ' automatic DOI generation');
    this.workflowsService.autoGenerateDois(entry.id, { autoGenerateDois: isAutoDoiEnabled }).subscribe(
      (response) => {
        this.alertService.detailedSuccess();
        this.workflowService.setWorkflow({ ...this.workflowQuery.getActive(), autoGenerateDois: response });
      },
      (error) => {
        this.alertService.detailedError(error);
      }
    );
  }

  requestDoiAccessLink(entry: Workflow): Observable<AccessLink> {
    this.alertService.start('Creating DOI edit link');
    return this.workflowsService.requestDOIEditLink(entry.id).pipe(
      tap(() => this.alertService.detailedSuccess()),
      catchError((error) => {
        this.alertService.detailedError(error);
        throw throwError(error);
      })
    );
  }

  deleteDoiAccessLink(entry: Workflow) {
    this.alertService.start('Deleting DOI edit link');
    this.workflowsService.deleteDOIEditLink(entry.id).subscribe(
      () => {
        this.alertService.detailedSuccess();
      },
      (error) => {
        this.alertService.detailedError(error);
      }
    );
  }
}
