name: Update license file

on:
  push:
    branches:
      - 'dependabot/**'

jobs:
  update_license_file:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install git-secrets 
        run: npm run install-git-secrets

      - name: Update license file
        run: npm run license

      - name: Push changes if license file changed
        run: |
          if [ -n "$(git status --porcelain | grep "THIRD-PARTY-LICENSES.csv")" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add THIRD-PARTY-LICENSES.csv
            git commit -m "Update license file"
            git push
          else
            echo "There were no changes to THIRD-PARTY-LICENSE.csv"
          fi
